//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teste_19_10_14.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cargo
    {
        public cargo()
        {
            this.funcionario = new HashSet<funcionario>();
        }
    
        public decimal ID_CARGO { get; set; }
        public string DESCRICAO { get; set; }
    
        public virtual ICollection<funcionario> funcionario { get; set; }
    }
}
