//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teste_19_10_14.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class funcionario
    {
        public int Id { get; set; }
        public string NOME { get; set; }
        public Nullable<decimal> ID_CARGO { get; set; }
        public System.DateTime DATA_ENTRADA { get; set; }
        public Nullable<decimal> SALARIO { get; set; }
    
        public virtual cargo cargo { get; set; }
    }
}
